class HTMLGen:
  def __init__(self):
    pass
  def a(self,s):
    return f'<a>{s}</a>'
  def b(self,s):
    return f'<b>{s}</b>'
  def p(self,s):
    return f'<p>{s}</p>'
  def body(self,s):
    return f'<body>{s}</body>'
  def div(self,s):
    return f'<div>{s}</div>'
  def span(self,s):
    return f'<span>{s}</span>'
  def title(self,s):
    return f'<title>{s}</title>'
  def comment(self,s):
        return f'<!--{s}-->'